"use strict";

const chatbotConfig = {
  enabled: true,
  widget: {
    title: "Assistant BedTrip",
    subtitle: "Réponses rapides",
    greeting:
      "Bonjour. Je peux vous aider pour la réservation, le paiement, l'annulation ou les services de chambre.",
    placeholder: "Écrivez votre question...",
    openDelayMs: 9000,
    supportedRoutes: [
      "search-landing",
      "search-results",
      "hotel-detail",
      "booking",
      "booking-finished",
      "payment-success",
      "payment-error",
      "blog-index",
      "blog-post",
      "conditions",
    ],
    colors: {
      primary: "#a5141e",
      primaryDark: "#7f1017",
      surface: "#ffffff",
    },
    quickActions: [
      { id: "hotel_info", label: "Petit-déjeuner", message: "Le petit-déjeuner est-il inclus ?" },
      { id: "promo_codes", label: "Codes promo", message: "Quels codes promo sont disponibles ?" },
      { id: "best_destinations", label: "Destinations", message: "Quelles sont les meilleures destinations ?" },
      { id: "payment_info", label: "Paiement", message: "Comment fonctionne le paiement ?" },
      { id: "cancellation_policy", label: "Annulation", message: "Quelles sont les conditions d'annulation ?" },
      { id: "booking_confirmation", label: "Bon hôtel", message: "Quand vais-je recevoir mon bon de réservation ?" },
    ],
  },
  quickReplies: {
    search_hotel: { label: "Chercher un hôtel", message: "Comment chercher un hôtel ?" },
    hotel_info: { label: "Infos hôtel", message: "Le petit-déjeuner est-il inclus ?" },
    promo_codes: { label: "Codes promo", message: "Quels codes promo sont disponibles ?" },
    best_destinations: { label: "Destinations", message: "Quelles sont les meilleures destinations ?" },
    booking_help: { label: "Modifier", message: "Can I modify my booking?" },
    payment_info: { label: "Paiement", message: "Can I pay in installments?" },
    cancellation_policy: { label: "Annulation", message: "Do you have free cancellation?" },
    booking_confirmation: { label: "Confirmation", message: "I did not receive my confirmation" },
    contact_support: { label: "Support", message: "How do I contact support?" },
  },
  intents: [
    {
      name: "greeting",
      priority: 4,
      keywords: ["bonjour", "bonsoir", "salut", "hello", "hi"],
      responseHandler: "greeting",
      quickReplies: ["search_hotel", "hotel_info", "payment_info", "cancellation_policy"],
    },
    {
      name: "search_hotel",
      priority: 6,
      keywords: [
        "chercher",
        "recherche",
        "search hotel",
        "find hotel",
        "hotel",
        "hôtel",
        "destination",
        "date",
        "voyageur",
        "adulte",
        "enfant",
      ],
      response:
        "Utilisez la recherche BedTrip avec destination, dates et voyageurs. Ensuite, comparez les hôtels et choisissez une chambre avant de passer à la réservation.",
      quickReplies: ["hotel_info", "cancellation_policy", "payment_info"],
    },
    {
      name: "hotel_info",
      priority: 10,
      keywords: [
        "petit dejeuner",
        "petit-déjeuner",
        "breakfast",
        "breakfast included",
        "included breakfast",
        "check in",
        "check-in",
        "checkin",
        "arrival time",
        "heure arrivee",
        "heure arrivée",
        "dej",
        "déjeuner",
        "repas",
        "meal",
        "colazione",
        "desayuno",
        "kahvalti",
      ],
      responseHandler: "hotelInfo",
      quickReplies: ["cancellation_policy", "payment_info", "contact_support"],
    },
    {
      name: "promo_codes",
      priority: 11,
      keywords: [
        "promo",
        "promocode",
        "code promo",
        "codes promo",
        "code promotion",
        "promotion",
        "coupon",
        "voucher discount",
        "discount",
        "reduction",
        "réduction",
        "remise",
        "offre",
        "offres",
        "bon plan",
        "summer10",
      ],
      responseHandler: "promoCodes",
      quickReplies: ["best_destinations", "search_hotel", "payment_info", "contact_support"],
    },
    {
      name: "best_destinations",
      priority: 9,
      keywords: [
        "destination",
        "destinations",
        "meilleure destination",
        "meilleures destinations",
        "best destination",
        "best destinations",
        "ou aller",
        "où aller",
        "idee voyage",
        "idée voyage",
        "inspiration",
        "travel ideas",
        "vacances",
        "voyage",
        "blog",
      ],
      responseHandler: "bestDestinations",
      quickReplies: ["search_hotel", "promo_codes", "contact_support"],
    },
    {
      name: "booking_help",
      priority: 8,
      keywords: [
        "modifier",
        "modify",
        "change booking",
        "change reservation",
        "edit booking",
        "booking help",
        "reservation help",
        "reservation",
        "réservation",
        "booking",
        "commande",
        "order",
        "reference",
        "référence",
        "booking reference",
        "partner order",
        "token",
      ],
      responseHandler: "bookingHelp",
      quickReplies: ["booking_confirmation", "contact_support", "payment_info"],
    },
    {
      name: "payment_info",
      priority: 8,
      keywords: [
        "paiement",
        "payer",
        "carte",
        "card",
        "credit card",
        "cb",
        "installment",
        "installments",
        "3x",
        "4x",
        "systempay",
        "floa",
        "cofidis",
        "payment",
        "pay",
        "banque",
        "bank",
        "checkout",
      ],
      responseHandler: "paymentInfo",
      quickReplies: ["booking_confirmation", "cancellation_policy", "contact_support"],
    },
    {
      name: "cancellation_policy",
      priority: 9,
      keywords: [
        "annulation",
        "annuler",
        "remboursable",
        "remboursement",
        "remboursement reservation",
        "remboursement booking",
        "remboursable reservation",
        "refund",
        "refund booking",
        "refund reservation",
        "refundable",
        "cancel",
        "cancel booking",
        "cancel reservation",
        "can i cancel",
        "can i stop booking",
        "stop booking",
        "stop reservation",
        "change my mind",
        "free cancellation",
        "cancellation policy",
        "politique annulation",
        "iptal",
        "iade",
      ],
      responseHandler: "cancellationPolicy",
      quickReplies: ["payment_info", "booking_confirmation", "contact_support"],
    },
    {
      name: "booking_confirmation",
      priority: 8,
      keywords: [
        "bon",
        "bon hotel",
        "voucher",
        "hotel voucher",
        "confirmation",
        "confirmation email",
        "did not receive",
        "didnt receive",
        "not receive confirmation",
        "no email",
        "document",
        "recu",
        "reçu",
        "receipt",
        "email",
        "mail",
      ],
      responseHandler: "bookingConfirmation",
      quickReplies: ["booking_help", "payment_info", "contact_support"],
    },
    {
      name: "contact_support",
      priority: 10,
      keywords: [
        "contact",
        "support",
        "aide",
        "help",
        "humain",
        "human",
        "agent",
        "telephone",
        "téléphone",
        "phone",
        "email support",
        "mail support",
        "adresse email",
      ],
      responseHandler: "contactSupport",
      quickReplies: ["booking_help", "payment_info"],
    },
    {
      name: "fallback",
      priority: 0,
      keywords: [],
      response:
        "Sorry, I did not fully understand. Can you rephrase your question about hotel search, booking, payment, cancellation, breakfast, check-in or confirmation?",
      quickReplies: ["payment_info", "cancellation_policy", "contact_support"],
    },
  ],
  fallback: {
    message:
      "Je n'ai pas trouvé de réponse sûre pour cette question. Reformulez avec des mots comme paiement, annulation, petit-déjeuner, réservation ou bon hôtel.",
    quickReplies: [
      { label: "Paiement", message: "Comment fonctionne le paiement ?" },
      { label: "Annulation", message: "Quelles sont les conditions d'annulation ?" },
      { label: "Contact", message: "Comment contacter le support ?" },
    ],
  },
  escalation: {
    label: "Contacter le support",
    message:
      "Pour une demande précise sur une réservation, gardez votre référence partenaire et contactez le support BedTrip.",
  },
  contact: {
    phoneLabel: "02 35 08 22 49",
    phoneHref: "tel:+33235082249",
    email: "kotanvoyages@outlook.com",
  },
  links: {
    blog: "/blog",
  },
};

module.exports = chatbotConfig;
